//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInvalidCodeMeli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class amozeshEntities : DbContext
    {
        public amozeshEntities()
            : base("name=amozeshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fostad> fostads { get; set; }
        public virtual DbSet<fostad_head> fostad_head { get; set; }
        public virtual DbSet<vOs_tb_TheseDb> vOs_tb_TheseDb { get; set; }
    
        [DbFunction("amozeshEntities", "fn_GetInvalidNationalCodesList")]
        public virtual IQueryable<fn_GetInvalidNationalCodesList_Result> fn_GetInvalidNationalCodesList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetInvalidNationalCodesList_Result>("[amozeshEntities].[fn_GetInvalidNationalCodesList]()");
        }
    }
}
