//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInvalidCodeMeli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fostad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fostad()
        {
            this.fostad_head = new HashSet<fostad_head>();
        }
    
        public decimal code_ostad { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string namep { get; set; }
        public string idd { get; set; }
        public string idd_meli { get; set; }
        public byte sex { get; set; }
        public string nsex { get; set; }
        public Nullable<decimal> idmadrak { get; set; }
        public string namemadrak { get; set; }
        public Nullable<decimal> idresh { get; set; }
        public string nameresh { get; set; }
        public Nullable<decimal> martabeh { get; set; }
        public string namemartabeh { get; set; }
        public Nullable<decimal> nahveh_hamk { get; set; }
        public string name_nahveh { get; set; }
        public Nullable<decimal> saat_movazaf { get; set; }
        public Nullable<decimal> code_sazman { get; set; }
        public string sal_tav { get; set; }
        public Nullable<decimal> mahal_tav { get; set; }
        public string name_mahal_tav { get; set; }
        public Nullable<decimal> mahal_sodor { get; set; }
        public string name_mahal_sodor { get; set; }
        public string sal_madrak { get; set; }
        public Nullable<decimal> keshvar { get; set; }
        public string name_keshvar { get; set; }
        public Nullable<int> type_university { get; set; }
        public string nametypeuniversity { get; set; }
        public Nullable<decimal> university { get; set; }
        public string nameuniversity { get; set; }
        public Nullable<decimal> idgroup { get; set; }
        public string namegroup { get; set; }
        public string date_est { get; set; }
        public Nullable<int> vaz_fali { get; set; }
        public string name_vaz { get; set; }
        public Nullable<decimal> type_est { get; set; }
        public string name_type_est { get; set; }
        public string add_kar { get; set; }
        public string add_hom { get; set; }
        public string tel_kar { get; set; }
        public string tel_hom { get; set; }
        public Nullable<int> saat_tadris { get; set; }
        public string add_email { get; set; }
        public Nullable<byte> semat { get; set; }
        public string siba { get; set; }
        public string mobile { get; set; }
        public string code_posti { get; set; }
        public Nullable<decimal> rial_ost { get; set; }
        public Nullable<decimal> rial_ost2 { get; set; }
        public string payeh { get; set; }
        public string add_email2 { get; set; }
        public Nullable<long> ozv_elmi { get; set; }
        public string sanavat_azad { get; set; }
        public string sanavat_vahed { get; set; }
        public string hamkari_pp { get; set; }
        public string avrg_tadris { get; set; }
        public string hamkar_out { get; set; }
        public string tadris_magh { get; set; }
        public string vaz_nomreh { get; set; }
        public string shekayat { get; set; }
        public Nullable<byte> ConvertData { get; set; }
        public Nullable<decimal> os_idresh { get; set; }
        public Nullable<int> saat_tad1 { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
        public string arzeshost { get; set; }
        public string citybank { get; set; }
        public string citybsnk { get; set; }
        public string shobbank { get; set; }
        public string codebank { get; set; }
        public Nullable<decimal> old_code { get; set; }
        public Nullable<decimal> aa { get; set; }
        public Nullable<byte> omomi { get; set; }
        public Nullable<byte> elmi { get; set; }
        public Nullable<byte> nezam { get; set; }
        public string date_elmi { get; set; }
        public string num_elmi { get; set; }
        public string date_omomi { get; set; }
        public string num_omomi { get; set; }
        public string sharh { get; set; }
        public string DATE_TAV { get; set; }
        public Nullable<byte> NATIONALITY { get; set; }
        public string CODE_BIMEH { get; set; }
        public string CODE_BAYEGAN { get; set; }
        public Nullable<bool> SMS_WEB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fostad_head> fostad_head { get; set; }
    }
}
